### ISSUE TITLE
Question about the confusion matrix

### ISSUE THREAD

**Issue by JiaxuanChenjohnson** [wuwenxuan0226/Pointnet2_Radar.PyTorch#1]
Hi! I have trouble reproducing the result you posted. On the train dataset I achieved similar values as the confusion matrix, but on the test dataset, it's far from good. Your confusion matrix is based on train or validation dataset? Thanks for answering!

**Comment by wuwenxuan0226** [comment]
Please try to merge two datasets, the result is so long ago that I can't remember it. Sorry about it.

**Comment by wuwenxuan0226** [comment]
After combine two dataset, please check the 'Absolute Confusion Metrics', see if the total detection number is similar.
